project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "US Cancer Analysis"
  author:
    - Nafisa Ali (na3070)
    - Yu He (yh3659)
  repo-url: https://github.com/yuhe6/Cancer_Analysis
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


